### ISSUE TITLE
[ SUGGESTION ] Add more Pokemon Pets and Cartoon Characters

### ISSUE THREAD

**Issue by crashzk** [hallucinogenic/CS-GO-Ported-Models#1]
It would be possible to add more Pokemon pets and add pets from animal designs, such as Tom & Jerry, and others.

**Comment by hallucinogenic** [comment]
This repository is for only models that I've ported (without editing animations and their model as well), from another Games.
Maybe I'll change the repo and add more things than models, but idk yet.
