### ISSUE TITLE
Doubt with pets directory paths

### ISSUE THREAD

**Issue by paulocrash** [hallucinogenic/CS-GO-Ported-Models#2]
I saw in the pets' config that you set up in two ways.

The pet Jolteon is configured like this: https://github.com/hallucinogenic/CS-GO-Pet-Models/blob/master/Pok%C3%A9mon/Jolteon/materials/models/pets/pokemon/jolteon/Thunders.vmt

The pet Umbreon is configured like this: https://github.com/hallucinogenic/CS-GO-Pet-Models/blob/master/Pok%C3%A9mon/Umbreon/materials/models/htconfigs/pets/pokemon/umbreon/Blacky.vmt

As you can see one has the bars "\\" while the other has the "/" bars.

Would it make a difference, would it be a mistake?

I do not know if there's more, I just saw this one.

**Comment by paulocrash** [comment]
Another problem is also that none of the Pets Pokemon show the pet, buy and become invisible.

http://prntscr.com/jgvad8

**Comment by hallucinogenic** [comment]
About the "\", I'm using a batch file made by Boomix that create a TXT file with all the file paths.
I change everytime to "/", but maybe I forgot that one.

About that print, make sure that your files are correct in the server (and also in the FastDL).

**Comment by paulocrash** [comment]
Perfect, I'll be checking the "/" if everyone is correct.

Regarding the files, I checked and everyone is on the server and FastDL in any case I will be checking again just to confirm and return the contact.

**Comment by paulocrash** [comment]
The Pokemons are all still invisible, select them in the Store, equip it and everything, but it shows nothing, it becomes invisible.

I've checked FastDL and are downloading them correctly, no problem.

I have already placed it manually in my CSGO and on the Server, and it still does not show too.
